"""
Internal tools for the budget-optimisation assignment.

These are MOCK versions of real Lifesight platform endpoints. They run fully offline
(no network, no credentials) but faithfully mirror the real API's method, params,
response shapes, and — importantly — its real-world messiness. Each tool's docstring
names the real endpoint it stands in for.

RULES FOR CANDIDATES:
  - Treat these as the ONLY source of truth. No web, no external calls.
  - Do NOT edit this file's behaviour. You may wrap it, cache it, slim its output.
  - Some tools are deliberately messy: huge responses, overlapping tools, strict
    param names, hard ordering dependencies, ambiguous business terms, and required
    inputs the user often omits. Handling that mess reliably is the assignment.

Envelope conventions (mirrors the real `make_api_request`):
  success -> {"status": "success", "data": <payload>}
  error   -> {"status": "error", "error_code": <int>, "error_message": <str>}

A tiny in-process SESSION dict simulates server-side state (like the real agent's
session state). Some tools READ state written by earlier tools — get the order wrong
and you get an error, not a guess.
"""

from __future__ import annotations

import random
from typing import Any

# --------------------------------------------------------------------------- #
# Simulated server-side session state (reset via reset_session()).
# --------------------------------------------------------------------------- #
SESSION: dict[str, Any] = {}


def reset_session() -> None:
    SESSION.clear()


def _ok(data: Any) -> dict[str, Any]:
    return {"status": "success", "data": data}


def _err(code: int, msg: str) -> dict[str, Any]:
    return {"status": "error", "error_code": code, "error_message": msg}


# --------------------------------------------------------------------------- #
# Canned data (deterministic — fixed seed).
# --------------------------------------------------------------------------- #
_RNG = random.Random(42)
_KPIS = ["Revenue", "Conversions", "Installs"]
_COUNTRIES = [("US", "USD"), ("DE", "EUR"), ("MX", "MXN"), ("IN", "INR"), ("GB", "GBP")]
_CHANNELS = [
    ("Google PMAX", "spend_google_pmax"),
    ("Google Branded Search", "spend_google_branded"),
    ("Meta BOF", "spend_meta_bof"),
    ("Meta Prospecting", "spend_meta_prospecting"),
    ("TikTok", "spend_tiktok"),
    ("CTV", "spend_ctv"),
    ("Snapchat", "spend_snap"),
]


def _make_models(n: int = 220) -> list[dict[str, Any]]:
    """~220 full model objects, each fat with junk — mirrors the real ~19MB /mmm/models.

    Only a few fields matter (id, modelName, outcomeKPI, modelStatus, createdAt,
    country, currency). The rest is provenance/plumbing you should slim away.
    """
    models = []
    for i in range(n):
        kpi = _RNG.choice(_KPIS)
        country, currency = _RNG.choice(_COUNTRIES)
        created = 1_700_000_000 + i * 90_000  # increasing => higher i is newer
        models.append({
            "id": 4_000_000_000_000_000 + i * 111_113,
            "modelName": f"model_{i}_{kpi.lower()}",
            "modelDisplayName": None if i % 3 else f"{kpi} Model {i}",
            "outcomeKPI": kpi,
            "modelStatus": "Success" if i % 7 else "Failed",
            "createdAt": {"seconds": created, "nanos": 0},
            "country": country,
            "currency": currency,
            "additiveModel": bool(i % 2),
            "solId": f"sol_{i:04d}",
            # ---- junk below: provenance/plumbing/raw internals (the fat) ----
            "gcsBucketName": "moda-mmm-artifacts-stg",
            "gcsPath": f"gs://moda-mmm-artifacts-stg/models/{i}/robyn_output/",
            "gcsPreviousPath": f"gs://moda-mmm-artifacts-stg/models/{i}/prev/",
            "fileName": f"input_{i}.csv",
            "previousSuccessFileName": f"input_{i}_prev.csv",
            "hyperParametersList": [{"name": f"hp_{k}", "value": _RNG.random()} for k in range(40)],
            "prophetVarsIds": [_RNG.randint(1, 9999) for _ in range(25)],
            "selectedSchema": {"cols": [f"col_{c}" for c in range(30)]},
            "rawTrainingWindow": [round(_RNG.random(), 5) for _ in range(60)],
            "refreshFrequency": _RNG.choice(["weekly", "monthly"]),
            "createdBy": "etl-service@moda", "updatedBy": "etl-service@moda",
            "lastUpdatedAt": {"seconds": created + 3600, "nanos": 0},
            "failedReason": None,
            "predictionAccuracy": round(_RNG.uniform(0.7, 0.95), 4),
        })
    return models


_MODELS = _make_models()
_MODELS_BY_ID = {str(m["id"]): m for m in _MODELS}


def _optimise_rows(total_budget: float, constraint_type: int) -> list[dict[str, Any]]:
    """Per-channel optimise rows in the REAL nested shape + an 'All Platforms' rollup."""
    rows = []
    total_opt_spend, total_opt_rev, total_cur_spend, total_cur_rev = 0.0, 0.0, 0.0, 0.0
    n = len(_CHANNELS)
    for idx, (name, col) in enumerate(_CHANNELS):
        cur_spend = 0.0 if idx == n - 1 else round(total_budget / n * _RNG.uniform(0.6, 1.4), 2)
        # aggressive (3) reallocates more than conservative (1)
        factor = {0: 1.0, 1: 1.05, 2: 1.2, 3: 1.6}.get(constraint_type, 1.05)
        opt_spend = round(cur_spend * _RNG.uniform(0.8, factor), 2)
        cur_rev = round(cur_spend * _RNG.uniform(2.0, 4.0), 2)
        opt_rev = round(opt_spend * _RNG.uniform(2.2, 4.5), 2)
        total_cur_spend += cur_spend; total_opt_spend += opt_spend
        total_cur_rev += cur_rev; total_opt_rev += opt_rev
        rows.append({
            "platformName": name,
            "excelColumnName": col,
            "currentBudgetData": {"spend": cur_spend, "revenue": cur_rev,
                                  "iROAS": round(cur_rev / cur_spend, 2) if cur_spend else 0},
            "optimisedBudgetData": {"spend": opt_spend, "response": opt_rev,
                                    "iROAS": round(opt_rev / opt_spend, 2) if opt_spend else 0},
            "totalOptimisedBudget": opt_spend,
            # raw saturation curve — big, rarely needed by the model
            "simulatedResponseCurveList": [{"spend": s * 1000, "revenue": s * 1000 * _RNG.uniform(2, 4)}
                                           for s in range(200)],
        })
    rows.append({
        "platformName": "All Platforms",
        "currentBudgetData": {"spend": round(total_cur_spend, 2), "revenue": round(total_cur_rev, 2)},
        "optimisedBudgetData": {"spend": round(total_opt_spend, 2), "response": round(total_opt_rev, 2),
                                "iROAS": round(total_opt_rev / total_opt_spend, 2) if total_opt_spend else 0},
        "totalOptimisedBudget": round(total_opt_spend, 2),
    })
    return rows


# =========================================================================== #
# 1. Model discovery
# =========================================================================== #
def list_models() -> dict[str, Any]:
    """Real: GET /mmm/models. Returns ALL models as full fat objects (~200, big).

    No pagination, no limit. This is the ~19MB blob. Newest is NOT guaranteed first.
    """
    return _ok(list(_MODELS))


def get_model_details(mmmRequestId: str) -> dict[str, Any]:
    """Real: GET /mmm/models/{id}. One full model object.

    NOTE: overlaps heavily with list_models — deciding when to use which (and not
    calling list_models just to read one model's fields) is part of the test.
    Param is camelCase.
    """
    m = _MODELS_BY_ID.get(str(mmmRequestId))
    if not m:
        return _err(404, f"model {mmmRequestId} not found")
    return _ok(dict(m))


def get_mmm_input(mmmRequestId: str) -> dict[str, Any]:
    """Real: GET /mmm/input. current_revenue = Sum(data.kpi[0].values)."""
    if str(mmmRequestId) not in _MODELS_BY_ID:
        return _err(404, f"model {mmmRequestId} not found")
    return _ok({"kpi": [{"name": "revenue", "values": [40000.0, 42000.0, 38000.0, 45000.0]}]})


# =========================================================================== #
# 2. Current budget — with an overlapping DEPRECATED twin (ambiguity trap)
# =========================================================================== #
def get_current_budget(mmmRequestId: str, is_additive_model: str = "false") -> dict[str, Any]:
    """Real: GET /v2/planner/current-budget. CANONICAL current-budget tool.

    Param MUST be camelCase `mmmRequestId` (snake_case is a different signature and
    will error). Response includes a large `referencePoint` decomposition you should
    slim before showing a model.
    """
    if str(mmmRequestId) not in _MODELS_BY_ID:
        return _err(404, f"model {mmmRequestId} not found")
    ref = {f"period_{p}": {"decompositionData": [
        {"variableName": col, "totalInput": round(_RNG.uniform(0, 5000), 2)} for _, col in _CHANNELS
    ]} for p in range(6)}
    return _ok({
        "startDate": "2025-12-02", "endDate": "2025-12-31",
        "mmmCurrentBudgetResponseList": [
            {"timePeriod": tp, "budget": b} for tp, b in
            [("week", 1_931_871), ("month", 8_279_449), ("quarter", 24_838_348)]
        ],
        "referencePoint": ref,
    })


def get_planner_budget(model_id: str) -> dict[str, Any]:
    """DEPRECATED. Real: GET /planner/budget (v1). Superseded by get_current_budget.

    Looks like it does the same job. It does NOT: snake_case param, a stale/different
    shape, and values that lag reality. Using this instead of get_current_budget is a
    correctness bug. It is here on purpose.
    """
    if str(model_id) not in _MODELS_BY_ID:
        return _err(404, f"model {model_id} not found")
    return _ok({"budget_by_channel": {name: 1234.0 for name, _ in _CHANNELS},
                "_note": "v1 legacy shape; stale; do not use for decisions"})


# =========================================================================== #
# 3. Optimise pipeline — hard ordering dependency
# =========================================================================== #
def run_default_optimise(mmmRequestId: str, timePeriod: str = "quarter") -> dict[str, Any]:
    """Real: POST /v2/planner/budget-optimise (baseline). Establishes the baseline.

    Stage 1. MUST run before run_constrained_optimise. Writes server state.
    """
    if str(mmmRequestId) not in _MODELS_BY_ID:
        return _err(404, f"model {mmmRequestId} not found")
    SESSION["default_done"] = True
    SESSION["default_model"] = str(mmmRequestId)
    SESSION["timePeriod"] = timePeriod
    return _ok({"baseline": "ready", "mmmRequestId": str(mmmRequestId), "timePeriod": timePeriod})


def run_constrained_optimise(mmmRequestId: str, totalBudget: float,
                             constraintType: int) -> dict[str, Any]:
    """Real: POST /v2/planner/budget-optimise (core). Constrained allocation.

    Stage 2. ERRORS unless run_default_optimise ran first for the same model.
    constraintType: 0=Current, 1=Conservative, 2=Moderate, 3=Aggressive.
    totalBudget REQUIRED and must be > 0. Returns the big dateRangeToResponseMap.
    """
    if not SESSION.get("default_done") or SESSION.get("default_model") != str(mmmRequestId):
        return _err(409, "run_default_optimise must succeed for this model before constrained optimise")
    if totalBudget is None or float(totalBudget) <= 0:
        return _err(400, "totalBudget is required and must be > 0")
    if constraintType not in (0, 1, 2, 3):
        return _err(400, "constraintType must be one of 0,1,2,3")
    rows = _optimise_rows(float(totalBudget), int(constraintType))
    result = {"dateRangeToResponseMap": {
        "aggregated_aggregated": {"mmmBudgetOptimisationResponseList": rows},
        "range_0": {"budgetRequestId": 90_001},
    }}
    SESSION["optimisation_result"] = result
    SESSION["last_total_budget"] = float(totalBudget)
    return _ok(result)


def forecast_revenue(mmmRequestId: str) -> dict[str, Any]:
    """Real: POST /v2/planner/forecast-revenue. Forecast from the constrained result.

    ERRORS unless run_constrained_optimise ran first (needs its budgetRequestId + the
    model's solId). Returns weekly forecast series (slim before returning to the LLM).
    """
    if "optimisation_result" not in SESSION:
        return _err(409, "run_constrained_optimise must succeed before forecast_revenue")
    m = _MODELS_BY_ID.get(str(mmmRequestId))
    if not m:
        return _err(404, f"model {mmmRequestId} not found")
    weekly = [{"week": w, "forecast": round(200000 * (1 + w * 0.01), 2)} for w in range(52)]
    return _ok({"totalForecastRevenue": round(sum(x["forecast"] for x in weekly), 2),
                "weekly": weekly, "solId": m["solId"]})


# =========================================================================== #
# 4. Scenarios (multi-scenario compare) + target-KPI math
# =========================================================================== #
def save_scenario(label: str) -> dict[str, Any]:
    """Save the current optimisation_result under a label (in-memory)."""
    if "optimisation_result" not in SESSION:
        return _err(409, "nothing to save — run a constrained optimise first")
    SESSION.setdefault("scenarios", {})[label] = {
        "optimisation_result": SESSION["optimisation_result"],
        "total_budget": SESSION.get("last_total_budget"),
    }
    return _ok({"saved": label, "all": list(SESSION["scenarios"])})


def compare_scenarios(labels: list[str]) -> dict[str, Any]:
    """Compare saved scenarios IN MEMORY (no endpoint). Revenue/ROAS/allocation deltas."""
    saved = SESSION.get("scenarios", {})
    missing = [x for x in labels if x not in saved]
    if missing:
        return _err(404, f"scenarios not saved: {missing}")
    out = {}
    for lbl in labels:
        rows = saved[lbl]["optimisation_result"]["dateRangeToResponseMap"]["aggregated_aggregated"]["mmmBudgetOptimisationResponseList"]
        ap = next((r for r in rows if r.get("platformName") == "All Platforms"), {})
        rev = (ap.get("optimisedBudgetData") or {}).get("response")
        bud = saved[lbl]["total_budget"]
        out[lbl] = {"total_budget": bud, "optimised_revenue": rev,
                    "roas": round(rev / bud, 2) if rev and bud else None}
    return _ok({"scenario_count": len(out), "scenarios": out})


def calculate_target_budget(target_revenue: float, current_revenue: float,
                            all_platform_revenue: float) -> dict[str, Any]:
    """Pure math (NO endpoint): required_budget = target - current + all_platform_revenue."""
    return _ok({"required_budget": float(target_revenue) - float(current_revenue) + float(all_platform_revenue),
                "formula": "target_revenue - current_revenue + all_platform_revenue"})


# =========================================================================== #
# 5. Metadata (enums + business rules)
# =========================================================================== #
# NOTE: there is deliberately NO glossary / term->field lookup tool. Mapping a user's
# words ("revenue", "conversions", "spend") to the right fields, and spotting when a
# term is ambiguous, is YOUR job. Ground it in the actual tool responses and the
# metadata below. Do not guess a field name, and do not invent a metric a model does
# not produce (a model's outcomeKPI is one of Revenue / Conversions / Installs).
def channel_metadata() -> dict[str, Any]:
    """Enum dictionary + business rules. e.g. a 0 in currentBudgetData.spend = LOCKED channel."""
    return _ok({
        "constraint_type_ids": {"Current": 0, "Conservative": 1, "Moderate": 2, "Aggressive": 3},
        "zero_spend_meaning": "a channel with currentBudgetData.spend == 0 is LOCKED, not missing",
        "scenario_enums": ["max_response", "Target KPI"],
        "channels": [{"platformName": n, "excelColumnName": c} for n, c in _CHANNELS],
    })


# The full internal toolbox exposed to candidates.
TOOLBOX = [
    list_models, get_model_details, get_mmm_input,
    get_current_budget, get_planner_budget,
    run_default_optimise, run_constrained_optimise, forecast_revenue,
    save_scenario, compare_scenarios, calculate_target_budget,
    channel_metadata,
]
